//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbScheduleModel : DbContext
    {
        public dbScheduleModel()
            : base("name=dbScheduleModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ScheduleMachine> ScheduleMachines { get; set; }
        public virtual DbSet<tblAccessGroupChild> tblAccessGroupChilds { get; set; }
        public virtual DbSet<tblAccessGroupMaster> tblAccessGroupMasters { get; set; }
        public virtual DbSet<tblAccessMenuMaster> tblAccessMenuMasters { get; set; }
        public virtual DbSet<tblAssignEmployeeGroup> tblAssignEmployeeGroups { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblHistory> tblHistories { get; set; }
        public virtual DbSet<tblMachineCreation> tblMachineCreations { get; set; }
        public virtual DbSet<tblPayroll> tblPayrolls { get; set; }
        public virtual DbSet<tblScheduleMaster> tblScheduleMasters { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblSite> tblSites { get; set; }
        public virtual DbSet<tblWorkFlowChild> tblWorkFlowChilds { get; set; }
        public virtual DbSet<tblWorkFlowMaster> tblWorkFlowMasters { get; set; }
    }
}
