//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessMenuMaster
    {
        public long menu_Id { get; set; }
        public string menu_Name { get; set; }
        public string menu_Link { get; set; }
        public string menu_Icon { get; set; }
    }
}
