//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessGroupChild
    {
        public long groupChild_Id { get; set; }
        public Nullable<long> group_Id { get; set; }
        public Nullable<long> menu_Id { get; set; }
        public string access_Create { get; set; }
        public string access_Modify { get; set; }
        public string access_Delete { get; set; }
        public string access_View { get; set; }
    }
}
