//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public long Employee_Id { get; set; }
        public long Employee_Department { get; set; }
        public long Employee_Designation { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Email { get; set; }
        public string Employee_Contact { get; set; }
        public string Employee_Password { get; set; }
        public string Employee_Type { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FirstTimeLoginStatus { get; set; }
        public Nullable<long> group_Id { get; set; }
        public string Employee_Address { get; set; }
        public string Department_UserType { get; set; }
        public string HeadType { get; set; }
        public Nullable<long> UserHead_Id { get; set; }
        public Nullable<long> TotalNoOfLeaves { get; set; }
        public string EmpProfilePhoto { get; set; }
        public string grpid { get; set; }
        public string Remark { get; set; }
    }
}
