//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    using TrainningManagement.CommonClass;

    public partial class tblEmployee
    {
        public long Employee_Id { get; set; }
        public long Employee_Department { get; set; }
        public long Employee_Designation { get; set; }
        public string EmpID { get; set; }
        public string EmpProfilePhoto { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Contact { get; set; }
        public string Employee_Email { get; set; }
        public string Employee_Address { get; set; }
        public Nullable<long> group_Id { get; set; }
        public string Employee_UserName { get; set; }
        public string Employee_Password { get; set; }
        public string Status { get; set; }
        public string FirstTimeLoginStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> SiteId { get; set; }
        public NewAdd otherdata { get; set; }
    }
}
