//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory
    {
        public long H_Id { get; set; }
        public Nullable<long> Emp_Id { get; set; }
        public string Old_Action { get; set; }
        public string New_Action { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> EntryDatetime { get; set; }
        public Nullable<long> ActionRowId { get; set; }
        public string FromName { get; set; }
        public Nullable<long> Department_Id { get; set; }
        public string EmployeeName { get; set; }
    }
}
