//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachineCreation
    {
        public long Machine_Id { get; set; }
        public long Machine_Department { get; set; }
        public string Machine_Name { get; set; }
        public string Machine_Location { get; set; }
        public System.DateTime Machine_InstallationTime { get; set; }
        public string Machine_ScheduleType { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Calibration_Date { get; set; }
        public Nullable<System.DateTime> FirstDueCalibration_Date { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    }
}
