//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblPayroll
    {
        public long Payroll_Id { get; set; }
        public Nullable<long> Head_Id { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Reason { get; set; }
        public Nullable<long> NoOfDays { get; set; }
        public string EmergencyContactNo { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public string HeadName { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    }
}
