//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public long setting_Id { get; set; }
        public Nullable<long> Password_Limit { get; set; }
        public string Password_Security { get; set; }
        public string Password_age { get; set; }
        public string Password_Age_Notify { get; set; }
        public string Password_attempt_Limit { get; set; }
        public string Password_Reopen { get; set; }
        public string Password_History_Store_Limit { get; set; }
        public string Auto_Logout_Limit { get; set; }
        public string Login_For_All_Action { get; set; }
        public string Password_in_Logout { get; set; }
    }
}
