//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduleMaster
    {
        public long Schecule_Id { get; set; }
        public string Schedule_Name { get; set; }
        public string Schedule_Type { get; set; }
        public string Schedule_description { get; set; }
    }
}
